// UI
export const LOADING_UI = 'LOADING_UI'

// DOGS
export const SEARCH_BREED = 'SEARCH_BREED'
export const CLEAR_BREEDS = 'CLEAR_BREEDS'
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const UNFAVORITE_DOG = 'UNFAVORITE_DOG'

// Fetching all breeds
export const GET_ALL_BREEDS_REQUEST = 'GET_ALL_BREEDS_REQUEST';
export const GET_ALL_BREEDS_SUCCESS = 'GET_ALL_BREEDS_SUCCESS';
export const GET_ALL_BREEDS_FAILURE = 'GET_ALL_BREEDS_FAILURE';

export const SEARCH_BREED_REQUEST = 'SEARCH_BREED_REQUEST'
export const SEARCH_BREED_SUCCESS = 'SEARCH_BREED_SUCCESS'
export const SEARCH_BREED_FAILURE = 'SEARCH_BREED_FAILURE'

export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'